### ISSUE TITLE
Coalesced range sometimes comes up bogus.

### ISSUE THREAD

**Issue by mfeit-internet2** [mfeit-internet2/pscheduler-dev#12]
On some occasions, `coalesce_ranges()` comes up with an inverted range.

```
Traceback (most recent call last):
  File "./postrun.py", line 250, in <module>
    datetime.datetime.now(tzlocal()) # + pscheduler.iso8601_as_timedelta('PT2S')
  File "./postrun.py", line 145, in post_run
    schedule_range = pscheduler.coalesce_ranges( range_set, task_duration )
  File "/usr/lib/python2.6/site-packages/pscheduler/ranges.py", line 86, in coalesce_ranges
    "Came up with a bogus range %s - %s." % (str(final_lower), str(final_upper))
AssertionError: Came up with a bogus range 2016-03-17 12:20:16-04:00 - 2016-03-17 12:20:13-04:00.
```

**Comment by mfeit-internet2** [comment]
Fixed by commit 159cb83bbfc08a68d93e65fd51d62a635f304612.
